language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - unzip
      - curl
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - libssl-dev
      - libunwind8
      - zlib1g
      - libicu-dev
      - uuid-dev
mono:
  - 4.0.5
os:
  - linux
  - osx
osx_image: xcode7.1
install:
  - ./scripts/envsetup.sh
solution:
  ./HandyHelpers.sln
